---
title: "HPC/GPU cluster Terraform scripts"
description: "Terraform scripts deploying HPC/GPU cluster on OCI ver. 3.0"
schemaVersion: 1.0.0
version: "2023061301"
informationalText: "Terraform scripts deploying HPC/GPU cluster on OCI ver. 3.0"

# Code history
# 1.0: May 30th 2023: New release
# 2.0: Jun 17th 2023: Support resource manager stack
# 3.0: Aug 21st 2023: Support SMT and NPT BIOS settings

#source:
#  type: marketplace
#  reference: 67628143
locale: "en"

outputs:
  bastion:
    title: "Bastion Instance Public IP"
    type: copyableString
    visible: true

variableGroups:
  - title: "General options"
    variables:
      - ${sc_compartment_ocid}
      - ${sc_ad}
      - ${sc_ssh_key}
  - title: "Compute/GPU node options"
    variables:
      - ${sc_cn_display_name}
      - ${sc_cn_shape}
      - ${sc_cn_node_count}
      - ${sc_cn_image}
      - ${sc_cn_boot_vol_size}
      - ${sc_cn_cloud_config}
      - ${sc_cn_nps_x9}
      - ${sc_cn_nps_gpu40}
      - ${sc_cn_nps_gpu80}
      - ${sc_cn_smt}
  - title: "Hidden"
    variables:
      - ${inst_params_bast}
      - ${igw_display_name}
      - ${ngw_display_name}
      - ${rt_params}
      - ${sl_params}
      - ${vcn_params}
      - ${subnet_params}
      - ${user_name}
      - ${sc_cn_platformtype}
      - ${sc_cn_nps}
    visible: false

variables:
  sc_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Compartment where OCI resources reside"
    default: ${compartment_ocid}
    required: true
  sc_ad:
    type: oci:identity:availabilitydomain:name
    title: "Availability Domain"
    description: "Availability Domain where OCI resources reside"
    visible: complexExpression
    dependsOn:
      compartmentId: ${sc_compartment_ocid}
    required: true
  sc_ssh_key:
    type: oci:core:ssh:publickey
    title: "SSH public key"
    description: "SSH public key to login to Bastion"
    required: true
  sc_cn_display_name:
    title: "Display name postfix"
    description: "Compute/GPU node display name postfix ex) If x9-ol87, Compute/GPU node hostname becomes inst-xxxxx-x9-ol87"
    required: true
  sc_cn_shape:
    type: enum
    title: "Shape"
    description: "Compute/GPU node shape"
    enum:
      - "BM.Optimized3.36"
      - "BM.GPU4.8"
      - "BM.GPU.A100-v2.8"
    default: "BM.Optimized3.36"
    required: true
  sc_cn_node_count:
    type: integer
    title: "Node count"
    description: "Compute/GPU node count"
    minimum: 2
    default: 2
    required: true
  sc_cn_image:
    title: "Image OCID"
    description: "Compute/GPU node image OCID"
    required: true
  sc_cn_boot_vol_size:
    type: integer
    title: "Boot volume size"
    description: "Compute/GPU node boot volume size in GB"
    required: true
    minimum: 50
    default: 100
# "-" in variable name causes issue to handle its value in Terraform scripts
  sc_cn_cloud_config:
    type: file
    title: "cloud-config"
    description: "Compute/GPU node cloud-config file"
    required: true
  sc_cn_nps_x9:
    type: enum
    title: "NPS for BM.Optimized3.36"
    description: "Compute/GPU node NPS (NUMA nodes Per Socket) setting in BIOS for BM.Optimized3.36"
    enum:
      - "NPS1"
      - "NPS2"
    default: "NPS2"
    required: true
    visible:
      and: 
        - or:  
          - eq:
            - ${sc_cn_shape}
            - "BM.Optimized3.36"
  sc_cn_nps_gpu40:
    type: enum
    title: "NPS for BM.GPU4.8"
    description: "Compute/GPU node NPS (NUMA nodes Per Socket) setting in BIOS for BM.GPU4.8"
    enum:
      - "NPS0"
      - "NPS1"
      - "NPS2"
      - "NPS4"
    default: "NPS4"
    required: true
    visible:
      and: 
        - or:  
          - eq:
            - ${sc_cn_shape}
            - "BM.GPU4.8"
  sc_cn_nps_gpu80:
    type: enum
    title: "NPS for BM.GPU.A100-v2.8"
    description: "Compute/GPU node NPS (NUMA nodes Per Socket) setting in BIOS for BM.GPU.A100-v2.8"
    enum:
      - "NPS0"
      - "NPS1"
      - "NPS2"
      - "NPS4"
    default: "NPS4"
    required: true
    visible:
      and: 
        - or:  
          - eq:
            - ${sc_cn_shape}
            - "BM.GPU.A100-v2.8"
  sc_cn_smt:
    type: boolean
    title: "SMT"
    description: "Compute/GPU node SMT (Simultanious Multi Threading) enabled in BIOS"
    default: false
