---
title: HPC cluster
description: Oracle Cloud HPC cluster
schemaVersion: 1.1.0
version: "2021040901"
informationalText: Automated HPC cluster deployment
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=80357668

source:
  type: marketplace
  reference: 67628143
locale: "en"

outputs:
  bastion:
    title: "Bastion Instance Public IP"
    type: copyableString
    visible: true

variableGroups:
  - title: "Cluster configuration"
    variables:
      - ${targetCompartment}
      - ${ssh_key}
  - title: "Bastion options"
    variables:
      - ${ad}
      - ${bastion_shape}
  - title: "Compute/GPU node options"
    variables:
      - ${ad}
      - ${cn_shape}
      - ${cn_node_count}
      - ${cn_boot_volume_size}
      - ${use_marketplace_image}
      - ${use_old_marketplace_image}
      - ${compute_username}
      - ${marketplace_listing}
      - ${old_marketplace_listing}
      - ${unsupported}
      - ${compute_image_compartment}
      - ${image}
      - ${image_ocid}
  - title: "Network options"
    variables:
      - ${use_existing_vcn}
      - ${vcn_compartment}
      - ${vcn_id}
      - ${private_deployment}
      - ${public_subnet_id}
      - ${private_subnet_id}
      - ${vcn_subnet}
      - ${public_subnet}
      - ${private_subnet}
      - ${rdma_subnet}
      - ${additional_subnet}

  - title: "Hidden"
    variables:
      - ${region}
      - ${tenancy_ocid}
      - ${marketplace_listing_id}
      - ${marketplace_listing_id_GPU}
      - ${marketplace_listing_id_HPC}
      - ${ssh_cidr}
      - ${marketplace_source_images}
      - ${marketplace_version_id}
    visible: false
  - title: "Debug"
    variables: 
      - ${configure}
variables:
  targetCompartment:
    title: "target compartment"
    type: oci:identity:compartment:id
    default: ${compartment_ocid}
    required: true
  ad:
    type: oci:identity:availabilitydomain:name
    visible: complexExpression
    dependsOn:
      compartmentId: ${targetCompartment}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
  ssh_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    description: "Public SSH key"
    required: true
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${targetCompartment}
    required: true
    default: VM.Standard2.4
  cn_shape:
    type: enum
    enum:
      - "BM.HPC2.36"
      - "BM.GPU4.8"
      - "BM.GPU.B4.8"
      - "BM.GPU.A100-v2.8"
      - "BM.Optimized3.36"
    default: "BM.HPC2.36"
    title: "Shape of the Compute/GPU node"
    description: "Shape of compute nodes used in permanent/initial cluster"
    required: true
    visible:
      and:
        - ${cluster_network}

  cn_node_count:
    required: true
    type: integer
    minimum: 0
    title: "Initial cluster size"
    default: 2
    description: "Number of Compute Instances (Permanent Cluster when autoscaling)"

  cn_boot_volume_size:
    type: integer
    required: true
    minimum: 50
    title: "Size of the boot volume in GB"
    default: 50
    description: "Boot volume size in GB of each compute node" 

  use_marketplace_image:
    type: boolean
    title: "use marketplace image"
    description: "Use marketplace image, otherwise provide custom image OCID"
    default: true

  use_old_marketplace_image:
    type: boolean
    title: "use older marketplace images"
    description: "Images prior to September 2021"
    default: false
    visible:
      and:
        - ${use_marketplace_image}

  marketplace_listing:
    type: enum
    title: "Image version"
    description: "Marketplace listing to use"
    required: true
    enum:
      - "HPC_OL7"
      - "HPC_OL8"
      - "GPU"
    default: "HPC_OL7"
    visible:
      and:
        - ${use_marketplace_image}
        - not: 
          - ${use_old_marketplace_image}

  old_marketplace_listing:
    type: enum
    title: "Image version"
    description: "Marketplace listing to use"
    required: true
    enum:
      - "1. Oracle Linux 7.9 OFED 5.3-1.0.0.1 RHCK 20210607"
      - "2. Oracle Linux 7.8 OFED 5.0-1.0.0.0 UEK 20200826"
      - "3. Oracle Linux 7.7 OFED 4.4-2.0.7.0 UEK 20200229"
      - "4. Oracle Linux 7.9 OFED 5.0-2.1.8.0 RHCK 20210709"
    default: "4. Oracle Linux 7.9 OFED 5.0-2.1.8.0 RHCK 20210709"
    visible:
      and:
        - ${use_marketplace_image}
        - ${use_old_marketplace_image}

  compute_image_compartment:
    title: "compute image compartment"
    type: oci:identity:compartment:id
    default: ${targetCompartment}
    visible:
      and: 
        - not:
            - ${use_marketplace_image}
        - not:
            - ${unsupported}

  image:
    title: "Image"
    description: "Custom image ID for compute nodes"
    type: oci:core:image:id
    required: true
    dependsOn:
      compartmentId: ${compute_image_compartment}
    visible:
      and: 
        - not:
            - ${use_marketplace_image}
        - not:
            - ${unsupported}
  image_ocid:
    title: "Image OCID"
    description: "Custom image ID for compute nodes"
    type: string
    required: true
    visible:
      and: 
        - not:
            - ${use_marketplace_image}
        - and: 
            - ${unsupported}
  cluster_block_volume_size:
    required: true
    type: integer
    title: "Size of the additional volume in GB"
    default: 1000
    visible:
      and:
        - or:
            - and: 
                - eq:
                    - ${scratch_nfs_type_cluster}
                    - "block"
                - and:
                    - ${use_advanced}
                    - ${cluster_network}
                    - ${use_scratch_nfs}
            - and: 
                - eq:
                    - ${scratch_nfs_type_pool}
                    - "block"
                - and:
                    - not:
                        - ${cluster_network}
                    - and: 
                        - ${use_scratch_nfs}
                        - ${use_advanced}
  cluster_block_volume_performance:
    type: enum
    title: "Block volume performance"
    required: true
    enum:
      - "0.  Lower performance"
      - "10. Balanced performance"
      - "20. High Performance"
    default: "10. Balanced performance"
    visible:
      and:
        - or:
            - and: 
                - eq:
                    - ${scratch_nfs_type_cluster}
                    - "block"
                - and:
                    - ${cluster_network}
                    - ${use_scratch_nfs}
                    - ${use_advanced}
            - and: 
                - eq:
                    - ${scratch_nfs_type_pool}
                    - "block"
                - and:
                    - not:
                        - ${cluster_network}
                    - and: 
                        - ${use_scratch_nfs}
                        - ${use_advanced}
  use_existing_vcn:
    type: boolean
    title: "Use Existing VCN"
    description: "Use existing VCN or create new one. If true, make sure the security lists are correctly set in the subnets (ex: Open traffic within VCN)"
    default: false
  vcn_compartment:
    title: "VCN compartment"
    type: oci:identity:compartment:id
    visible: ${use_existing_vcn}
    default: ${targetCompartment}
    required: true
  vcn_id:
    type: oci:core:vcn:id
    visible:
      and:
        - ${use_existing_vcn}
    title: "Existing network"
    default: ''
    required: true
    dependsOn:
      compartmentId: ${vcn_compartment}
  public_subnet_id:
    title: Master Node Subnet
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${vcn_compartment}
      vcnId: ${vcn_id}
      hidePrivateSubnet: false
    # visible: 
      # and:
      #   - not:
      #     - ${private_deployment}
      #   - and: 
      #     - ${use_existing_vcn}
    visible: ${use_existing_vcn}  
    required: true
  private_subnet_id:
    title: Private Subnet
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${vcn_compartment}
      vcnId: ${vcn_id}
      hidePublicSubnet: true
    visible: ${use_existing_vcn}
    required: true
  vcn_subnet:
    type: string
    title: "VCN IP range"
    description: "VCN subnet"
    default: "172.16.0.0/21"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  public_subnet:
    type: string
    title: "Master Node subnet IP range"
    default: "172.16.0.0/24"
    description: "Must be within VCN subnet"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  additional_subnet:
    type: string
    title: "Additional subnet IP range"
    default: "172.16.1.0/24"
    description: "Must be within VCN subnet"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  rdma_subnet:
    type: string
    title: "RDMA subnet IP range"
    default: "192.168.168.0/22"
    description: "Must be the same size as private subnet"
    required: true
  private_subnet:
    type: string
    title: "Private subnet IP range"
    default: "172.16.4.0/22"
    description: "Must be within VCN subnet"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  configure: 
    type: boolean
    title: "Configure system"
    default: true
    description: "If unchecked, cluster will be launched but left unconfigured"

